store: store_a
raw_path: /Volumes/main/retail/product_files/store_a.csv
file_format: csv
target_table: main.retail_data.products
schema_mode: evolve
column_mappings:
  item_id: product_id
  cost_price: price
  item_desc: description
rules:
  drop_nulls: [item_id]
